### ISSUE TITLE
pgspeck_encrypt32 (and decrypt) should take int4

### ISSUE THREAD

**Issue by debackerl** [johto/pgspeck#1]
Hello,

Thanks for your nice library. However, pgspeck_encrypt32 should take an int4 for cleartext. In the C wrapper, you are casting it anyway. I don't understand why you expect an int8.

Thank you,
Laurent Debacker

**Comment by johto** [comment]
> Thanks for your nice library.

Glad you like it!

> However, pgspeck_encrypt32 should take an int4 for cleartext. In the C wrapper, you are casting it anyway. I don't understand why you expect an int8.

It's cast to _unsigned_ 32-bit integer, which isn't available in postgres on SQL level.  If you want to work with the 32-bit integers available in postgres by using the negative range, you can write such wrappers relatively easily.  I figured the interface was nicer this way, since most client applications have unsigned integers available and working only with non-negative integers is in my opinion a bit easier.
